Add retry logic for Notification service readiness in CI/CD workflow

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -161,6 +161,21 @@ jobs:
           done
           echo "API is ready!"
 
+      - name: Wait for Notfication service to be ready (5 retries)
+        run: |
+          MAX_RETRIES=5
+          COUNT=0
+          while ! curl -f http://localhost:5003; do
+            COUNT=$((COUNT+1))
+            if [ $COUNT -eq $MAX_RETRIES ]; then
+              echo "API failed to respond after $MAX_RETRIES attempts."
+              exit 1
+            fi
+            echo "Waiting for API... attempt $COUNT/$MAX_RETRIES"
+            sleep 10
+          done
+          echo "Notifiction service is ready!"
+
       - name: Run Backend Tests with Coverage
         run: |
           pytest fastapi_app/tests/ --cov=fastapi_app --cov-report=xml
